{"name": "Пользователь авторизуется с неверной почтой или паролем", "status": "passed", "steps": [{"name": "Проверяем вход с неверной почтой и паролем и получаем ошибку", "status": "passed", "steps": [{"name": "Войти в систему с неверной почтой или паролем", "status": "passed", "start": 1723291401654, "stop": 1723291401893}], "start": 1723291401654, "stop": 1723291401893}], "start": 1723291401654, "stop": 1723291401893, "uuid": "49c4c9a1-bc83-40b8-b555-e25af0e6a9f5", "historyId": "a7aaeab875304835cb483ed92ac7df8a", "testCaseId": "a7aaeab875304835cb483ed92ac7df8a", "fullName": "tests.test_login_user.TestLoginUser#test_login_invalid_credetentials_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-LQ0DQPC"}, {"name": "thread", "value": "11056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}